### ISSUE TITLE
AuditParser wants to grab mouse and then barfs

### ISSUE THREAD

**Issue by marcobelmonte** [mandiant/AuditParser#3]
Running Debian testing and I believe all required libraries are installed - this is what I get:

![image](https://f.cloud.github.com/assets/4238826/1196393/275a04e6-24ad-11e3-99d2-7bc5d8059b70.png)

Any ideas?

**Comment by ryankaz** [comment]
Hi Marco,

It looks like your shell is loading “AuditParser.py” as a shell script rather than as a python script (hence the “command not found errors”). You’ll need to prefix your command with “python” (assuming it is installed along with the necessary libraries) to ensure the script is interpreted properly.

Regards,

Ryan

**Comment by marcobelmonte** [comment]
Embarrassing, man - wish I could hide. For some reason I was thinking I could chmod and execute it... LOL. Fail. Thanks :-)

![image](https://f.cloud.github.com/assets/4238826/1197111/18b5b85e-24cb-11e3-87be-447faf366b34.png)

**Comment by ryankaz** [comment]
No problem! Glad it seems to be working now.

Make sure you also install “lxml” for python or you’ll get some more errors when you try to run the script against input data. If your python environment has “pip” set up you can just do “pip install lxml” to grab it.

**Comment by marcobelmonte** [comment]
Thanks, man - working great now - appreciate the tools you guys release independently and as an organization:

![image](https://f.cloud.github.com/assets/4238826/1197243/28edff74-24d0-11e3-92ac-c3894200c70f.png)
